--COUNTRY TABLEAdd commentMore actions
CREATE TABLE country
(
    id        bigint generated by default as identity primary key,
    name      VARCHAR(255) NOT NULL,
    continent VARCHAR(255) NOT NULL
);

-- AUTHOR TABLE
CREATE TABLE author
(
    id         bigint generated by default as identity primary key,
    name       VARCHAR(255) NOT NULL,
    surname    VARCHAR(255) NOT NULL,
    country_id BIGINT REFERENCES country (id)
);

--BOOK TABLE
CREATE TABLE book
(
    id               bigint generated by default as identity primary key,
    name             VARCHAR(255) NOT NULL,
    category         VARCHAR(255) NOT NULL,
    author_id        BIGINT REFERENCES author (id),
    available_copies INT,
    is_deleted       BOOLEAN DEFAULT FALSE,
    date_created     TIMESTAMP
);